### ISSUE TITLE
first article

### ISSUE THREAD

**Issue by sewera** [blazejsewera/blog#21]
Write the first article that will show in the blog.

```[tasklist]
### Tasks
- [x] Write a title
- [x] Write an abstract
- [x] Choose an image
- [x] Write the body of the article
- [x] Link and organize references in footnotes
```
